### ISSUE TITLE
Timer (and maybe other stuff) falls over when Facebook is down

### ISSUE THREAD

**Issue by chrylis** [m-h-c-t/mh-helper-extension#151]
Today is the day of the Great Facebook Outage of 2021, and the MHCT extension (Firefox) has stopped running the timer because of "cannot contact server". The timer part should work even if mhg is the only thing online.

**Comment by DevJackSmith** [comment]
Transferred issue to extension repo. good point. I'm assuming MH was still working? I don't see any dependencies in the extension that  are not included in the extension itself. Especially for popup page.

**Comment by DevJackSmith** [comment]
MH page has to be open and loaded in the same browser window I believe. But that's the only dependency

**Comment by DevJackSmith** [comment]
I didn't find any causes why it would stop working/dependencies. i'll try to keep an eye out for it, but i doubt FB will go down again anytime soon.

**Comment by DevJackSmith** [comment]
I would suggest playing on https://www.mousehuntgame.com instead of facebook, if facebook is having issues. The game itself might have some dependencies on fb, but the extension doesn't. In fact i'm using it with an ad blocker that blocks facebook, and it seems to work just fine. I'll close this for now, but if you notice it again on the https://www.mousehuntgame.com, let me know, and i'll reopen.
